#!/usr/bin/python3
import sys

def factorize(number):
    factors = []
    for i in range(2, number):
        if number % i == 0:
            factors.append((i, number // i))
    return factors

def process_file(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            number = int(line)
            factors = factorize(number)
            for factor in factors:
                print(f"{number}={factor[0]}*{factor[1]}")

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: factors <file>")
    else:
        file_path = sys.argv[1]
        process_file(file_path)
